apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-test-python-project
  labels:
    app: "ci-test-python-project"
    environment: "dev"
    region: "ric1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-test-python-project
  template:
    metadata:
      labels:
        app: "ci-test-python-project"
        environment: "dev"
        region: "ric1"
    spec:
      containers:
        - name: ci-test-python-project
          image: admarketplace/ci-test-python-project
          command:
            - "python"
            - "--version"
          resources:
            requests:
              cpu: ".1"
              memory: "200Mi"
            limits:
              cpu: ".2"
              memory: "200Mi"
      imagePullSecrets:
        - name: docker-registry-access-token-ampdockercirw
